version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building Next.js application...
      - npm run build
  post_build:
    commands:
      - echo Build completed, preparing artifacts...

artifacts:
  files:
    - '**/*'
  base-directory: '.'  # Root of your source directory, where your code is

cache:
  paths:
    - node_modules/**/*    # Cache node_modules to speed up subsequent builds

